### PR TITLE
Update PhotonVRPlayerBody.cs

### PR DESCRIPTION
**Pull request by MaxNiftyNine**
PhotonVRPlayerBody had a issue (mostly with gorilla locomotion) where you can turn your head sideways and the body will go through the floor, this should fix that bug.

### CODE REVIEW

**Comment by MaxNiftyNine** [comment]
I also just added GetCosmetic and edited the README to show how to use it

**Comment by fchb1239** [comment]
Can you explain the player body.cs a little better
Also that cosmetic code is already in the next update

**Comment by fchb1239** [comment]
playerbody.cs is flawed, the y axis of the body will only stay on the original y axis

**Comment by MaxNiftyNine** [comment]
Welp for me (gorilla locomotion) it solved the problem where the player model clips through the floor, it basically uses the same math as gorilla locomotion when finding where the capsule collider be

Whatever it's fine I'll make a new pull request if I want to add anything else

**Pull request closed without merging**
