### PR TITLE
Fixed PhotonVRPlayerBody from clipping through the floor with gorilla locomotion

### PR DESCRIPTION
**Pull request by MaxNiftyNine**
I did the thing again but this time it actually works lol

### CODE REVIEW

**Comment by MaxNiftyNine** [comment]
Also the bug (if you dont know what im talking) about is when your head (main camera) goes sideway, the body clips through the floor

**Comment by fchb1239** [comment]
Photon VR is not made for Gorilla Locomotion, this would error if the user did not have Gorilla Locomotion

**Comment by MaxNiftyNine** [comment]
How does it error out? Doesent make sense

**Comment by MaxNiftyNine** [comment]
Also I made a change so it's not gorilla locomotion but still fixes the problem

**Pull request closed without merging**
